server:
  port: 8765
spring:
  profiles:
    active: dev
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: eureka8765.com
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8764.com:8764/erueka/,http://eureka8766.com:8766/erueka/
---
server:
  port: 8762
spring:
  profiles:
    active: prod
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: eureka8762.com
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8761.com:8761/erueka/,http://eureka8763.com:8763/erueka/