server:
  port: 86
spring:
  profiles:
    active: dev
  application:
    name: consumer
  data:
    mongodb:
      uri: mongodb://localhost:27017/user

hystrix:
  metrics:
    enabled: true
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    instance-id: consumer-86
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8764.com:8764/eureka/,http://eureka8765.com:8765/eureka/,http://eureka8766.com:8766/eureka/

info:
  app.name: mathcer-top-it
  company.name: www.matcher.top.it.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 83
spring:
  profiles:
    active: prod
  application:
    name: consumer
  data:
    mongodb:
      uri: mongodb://localhost:27017/user

hystrix:
  metrics:
    enabled: true
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    instance-id: consumer-83
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/

info:
  app.name: mathcer-top-it
  company.name: www.matcher.top.it.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$