server:
  port: 85
spring:
  profiles:
    active: dev
  application:
    name: consumer
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
eureka:
  instance:
    instance-id: consumer-85
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8764.com:8764/erueka/,http://eureka8765.com:8765/erueka/,http://eureka8766.com:8766/erueka/
info:
  app.name: matcher-top-it
  company.name: www.matcher.top.it.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 82
spring:
  profiles:
    active: prod
  application:
    name: consumer
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
eureka:
  instance:
    instance-id: consumer-82
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/erueka/,http://eureka8762.com:8762/erueka/,http://eureka8763.com:8763/erueka/
info:
  app.name: matcher-top-it
  company.name: www.matcher.top.it.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$