server:
  port: 3344
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/choipin/matcher.git
  application:
    name: matcher