server:
  port: 8006
spring:
  profiles:
    active: dev
  application:
    name: provinder
  datasource:
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dev03
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.matcher.top.it.entity
hystrix:
  feign:
    enabled: true
eureka:
  instance:
    instance-id: provinder-8006
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8764.com:8764/eureka/,http://eureka8765.com:8765/eureka/,http://eureka8766.com:8766/eureka/
info:
  app.name: matcher-top-it
  company.name: www.matcher.top.it.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    name: provinder
  datasource:
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/prod03
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.matcher.top.it.entity
hystrix:
  feign:
    enabled: true
eureka:
  instance:
    instance-id: provinder-8003
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/
info:
  app.name: matcher-top-it
  company.name: www.matcher.top.it.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$