server:
  port: 8764
spring:
  profiles:
    active: dev
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: eureka8764.com
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8765.com:8765/eureka/,http://eureka8766.com:8766/eureka/
---
server:
  port: 8761
spring:
  profiles:
    active: prod
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: eureka8761.com
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/